"""
Forsaken Bot — Auth / Key Management cog

Admin commands (Founder role only):
  /genkey          — generate a key via modal
  /disablekey      — disable a key
  /deletekey       — delete a key
  /bulkdeletekeys  — delete multiple keys at once
  /managekey       — view/edit a single key
  /managekeys      — view/edit multiple keys
  /showallkeys     — list every key with full details
  /hwidreset       — reset HWID binding on one or more keys

Customer commands (Customer role only):
  /register        — claim a key and create login credentials
  /download        — get the download link
"""

import discord
from discord import app_commands, ui
from discord.ext import commands
import random
import string
from datetime import datetime, timezone

from cogs.database import (
    create_key, get_key, get_all_keys,
    disable_key, enable_key, delete_key, delete_keys,
    update_key, register_key, reset_hwid, key_exists,
)

# ─── Role IDs ─────────────────────────────────────────────────────────────────
FOUNDER_ROLE_ID  = 1510455747711074514
CUSTOMER_ROLE_ID = 1510457323162964008

# ─── Download link (set this in .env or replace the placeholder) ──────────────
import os
DOWNLOAD_LINK = os.getenv("DOWNLOAD_LINK", "https://PLACEHOLDER_SET_ME")


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _gen_key() -> str:
    """Generate a key in FORSAKEN-XXXX-XXXX-XXXX format."""
    chars = string.ascii_uppercase + string.digits
    segments = ["".join(random.choices(chars, k=4)) for _ in range(3)]
    return "FORSAKEN-" + "-".join(segments)


def _is_founder(member: discord.Member) -> bool:
    return any(r.id == FOUNDER_ROLE_ID for r in member.roles)


def _is_customer(member: discord.Member) -> bool:
    return any(r.id == CUSTOMER_ROLE_ID for r in member.roles)


def _fmt_ts(iso: str | None) -> str:
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(iso)
        return f"<t:{int(dt.timestamp())}:F>"
    except Exception:
        return iso


def _key_summary_lines(key: str, rec: dict, guild: discord.Guild | None = None) -> list[str]:
    """Return a list of lines describing a key record."""
    gen_user = "—"
    if guild and rec.get("generated_by"):
        m = guild.get_member(rec["generated_by"])
        gen_user = str(m) if m else f"<@{rec['generated_by']}>"

    claimed_user = "—"
    if guild and rec.get("claimed_by_discord"):
        m = guild.get_member(rec["claimed_by_discord"])
        claimed_user = str(m) if m else f"<@{rec['claimed_by_discord']}>"

    pw_display = f"||`{rec['password_hash'][:16]}…`||" if rec.get("password_hash") else "—"

    lines = [
        f"**Key:** `{key}`",
        f"**Duration:** {rec.get('duration', '—')}",
        f"**Status:** {'🔴 Disabled' if rec.get('disabled') else '🟢 Active'}",
        f"**Generated by:** {gen_user}  •  {_fmt_ts(rec.get('generated_at'))}",
        f"**Claimed by:** {claimed_user}",
        f"**Username:** `{rec.get('username') or '—'}`",
        f"**Password (hashed):** {pw_display}",
        f"**HWID:** `{rec.get('hwid') or '—'}`",
        f"**Registered:** {_fmt_ts(rec.get('registered_at'))}",
    ]
    return lines


# ══════════════════════════════════════════════════════════════════════════════
#  Modals
# ══════════════════════════════════════════════════════════════════════════════

class GenKeyModal(ui.Modal, title="Generate Key"):
    duration = ui.TextInput(
        label="Duration",
        placeholder="e.g. 30d, 7d, lifetime",
        style=discord.TextStyle.short,
        max_length=50,
    )
    note = ui.TextInput(
        label="Note (optional)",
        placeholder="e.g. for @username, promo, etc.",
        style=discord.TextStyle.short,
        max_length=200,
        required=False,
    )
    quantity = ui.TextInput(
        label="Quantity (1–25)",
        placeholder="1",
        style=discord.TextStyle.short,
        max_length=2,
        default="1",
    )

    async def on_submit(self, interaction: discord.Interaction):
        try:
            qty = max(1, min(25, int(self.quantity.value.strip())))
        except ValueError:
            qty = 1

        generated = []
        for _ in range(qty):
            key = _gen_key()
            # Avoid (extremely unlikely) collisions
            while key_exists(key):
                key = _gen_key()
            create_key(key, self.duration.value.strip(), interaction.user.id)
            generated.append(key)

        note_line = f"\n**Note:** {self.note.value.strip()}" if self.note.value.strip() else ""
        keys_block = "\n".join(generated)

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay(f"## {'Key' if qty == 1 else f'{qty} Keys'} Generated"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(
                f"**Duration:** {self.duration.value.strip()}{note_line}\n"
                f"**Generated by:** {interaction.user.mention}\n\n"
                f"```\n{keys_block}\n```"
            ),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Key Management"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


class RegisterModal(ui.Modal, title="Register — Claim Your Key"):
    key_input = ui.TextInput(
        label="Your Key",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX",
        style=discord.TextStyle.short,
        max_length=25,
    )
    username_input = ui.TextInput(
        label="Username",
        placeholder="Choose a username for the loader",
        style=discord.TextStyle.short,
        max_length=32,
    )
    password_input = ui.TextInput(
        label="Password",
        placeholder="Choose a password for the loader",
        style=discord.TextStyle.short,
        max_length=64,
    )

    async def on_submit(self, interaction: discord.Interaction):
        key      = self.key_input.value.strip().upper()
        username = self.username_input.value.strip()
        password = self.password_input.value.strip()

        if not key.startswith("FORSAKEN-"):
            await interaction.response.send_message(
                "Invalid key format. Keys look like `FORSAKEN-XXXX-XXXX-XXXX`.", ephemeral=True
            )
            return

        success, err = register_key(key, username, password, interaction.user.id)

        if not success:
            await interaction.response.send_message(f"Registration failed: **{err}**", ephemeral=True)
            return

        # Assign Customer role
        customer_role = interaction.guild.get_role(CUSTOMER_ROLE_ID)
        if customer_role and customer_role not in interaction.user.roles:
            try:
                await interaction.user.add_roles(customer_role, reason="Registered a Forsaken key")
            except discord.Forbidden:
                pass

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay("## Registration Successful"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(
                f"Your key has been claimed and your account is ready.\n\n"
                f"**Username:** `{username}`\n"
                f"**Key:** `{key}`\n\n"
                f"Use your **username** and **password** to log in to the loader.\n"
                f"Your HWID will be bound on first launch.\n\n"
                f"-# Keep your credentials safe — do not share them."
            ),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Registration"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


class DisableKeyModal(ui.Modal, title="Disable Key"):
    key_input = ui.TextInput(
        label="Key",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX",
        style=discord.TextStyle.short,
        max_length=25,
    )

    async def on_submit(self, interaction: discord.Interaction):
        key = self.key_input.value.strip().upper()
        if disable_key(key):
            await interaction.response.send_message(f"🔴 Key `{key}` has been **disabled**.", ephemeral=True)
        else:
            await interaction.response.send_message(f"Key `{key}` not found.", ephemeral=True)


class DeleteKeyModal(ui.Modal, title="Delete Key"):
    key_input = ui.TextInput(
        label="Key",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX",
        style=discord.TextStyle.short,
        max_length=25,
    )

    async def on_submit(self, interaction: discord.Interaction):
        key = self.key_input.value.strip().upper()
        if delete_key(key):
            await interaction.response.send_message(f"🗑️ Key `{key}` has been **deleted**.", ephemeral=True)
        else:
            await interaction.response.send_message(f"Key `{key}` not found.", ephemeral=True)


class BulkDeleteModal(ui.Modal, title="Bulk Delete Keys"):
    keys_input = ui.TextInput(
        label="Keys (one per line)",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX\nFORSAKEN-YYYY-YYYY-YYYY",
        style=discord.TextStyle.paragraph,
        max_length=2000,
    )

    async def on_submit(self, interaction: discord.Interaction):
        raw   = self.keys_input.value.strip().splitlines()
        keys  = [k.strip().upper() for k in raw if k.strip()]
        deleted, not_found = delete_keys(keys)

        lines = []
        if deleted:
            lines.append(f"**Deleted ({len(deleted)}):**\n```\n" + "\n".join(deleted) + "\n```")
        if not_found:
            lines.append(f"**Not found ({len(not_found)}):**\n```\n" + "\n".join(not_found) + "\n```")

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay("## Bulk Delete Result"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("\n\n".join(lines) or "Nothing to delete."),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Key Management"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


class ManageKeyModal(ui.Modal, title="Manage Key"):
    key_input = ui.TextInput(
        label="Key",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX",
        style=discord.TextStyle.short,
        max_length=25,
    )
    new_duration = ui.TextInput(
        label="New Duration (leave blank to keep)",
        placeholder="e.g. lifetime, 30d",
        style=discord.TextStyle.short,
        max_length=50,
        required=False,
    )
    toggle_disabled = ui.TextInput(
        label="Enable / Disable (enable | disable | leave blank)",
        placeholder="enable  or  disable",
        style=discord.TextStyle.short,
        max_length=10,
        required=False,
    )

    async def on_submit(self, interaction: discord.Interaction):
        key = self.key_input.value.strip().upper()
        rec = get_key(key)
        if not rec:
            await interaction.response.send_message(f"Key `{key}` not found.", ephemeral=True)
            return

        changes = []
        kwargs  = {}

        if self.new_duration.value.strip():
            kwargs["duration"] = self.new_duration.value.strip()
            changes.append(f"Duration → `{self.new_duration.value.strip()}`")

        toggle = self.toggle_disabled.value.strip().lower()
        if toggle == "disable":
            kwargs["disabled"] = True
            changes.append("Status → 🔴 Disabled")
        elif toggle == "enable":
            kwargs["disabled"] = False
            changes.append("Status → 🟢 Active")

        if kwargs:
            update_key(key, **kwargs)

        rec = get_key(key)  # reload
        summary = "\n".join(_key_summary_lines(key, rec, interaction.guild))
        change_text = "\n".join(changes) if changes else "No changes made."

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay(f"## Manage Key — `{key}`"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(f"**Changes applied:**\n{change_text}"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(summary),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Key Management"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


class ManageKeysModal(ui.Modal, title="Manage Multiple Keys"):
    keys_input = ui.TextInput(
        label="Keys (one per line)",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX\nFORSAKEN-YYYY-YYYY-YYYY",
        style=discord.TextStyle.paragraph,
        max_length=2000,
    )
    action = ui.TextInput(
        label="Action: enable | disable",
        placeholder="enable  or  disable",
        style=discord.TextStyle.short,
        max_length=10,
    )

    async def on_submit(self, interaction: discord.Interaction):
        raw    = self.keys_input.value.strip().splitlines()
        keys   = [k.strip().upper() for k in raw if k.strip()]
        action = self.action.value.strip().lower()

        if action not in ("enable", "disable"):
            await interaction.response.send_message(
                "Action must be `enable` or `disable`.", ephemeral=True
            )
            return

        ok, fail = [], []
        for k in keys:
            if action == "disable":
                result = disable_key(k)
            else:
                result = enable_key(k)
            (ok if result else fail).append(k)

        icon   = "🔴" if action == "disable" else "🟢"
        lines  = []
        if ok:
            lines.append(f"**{icon} {action.capitalize()}d ({len(ok)}):**\n```\n" + "\n".join(ok) + "\n```")
        if fail:
            lines.append(f"**Not found ({len(fail)}):**\n```\n" + "\n".join(fail) + "\n```")

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay(f"## Manage Keys — {action.capitalize()}"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("\n\n".join(lines) or "Nothing processed."),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Key Management"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


class HwidResetModal(ui.Modal, title="HWID Reset"):
    keys_input = ui.TextInput(
        label="Key(s) — one per line",
        placeholder="FORSAKEN-XXXX-XXXX-XXXX",
        style=discord.TextStyle.paragraph,
        max_length=2000,
    )

    async def on_submit(self, interaction: discord.Interaction):
        raw  = self.keys_input.value.strip().splitlines()
        keys = [k.strip().upper() for k in raw if k.strip()]

        ok, fail = [], []
        for k in keys:
            if reset_hwid(k):
                ok.append(k)
            else:
                fail.append(k)

        lines = []
        if ok:
            lines.append(f"**✅ HWID Reset ({len(ok)}):**\n```\n" + "\n".join(ok) + "\n```")
        if fail:
            lines.append(f"**Not found ({len(fail)}):**\n```\n" + "\n".join(fail) + "\n```")

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay("## HWID Reset"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(
                "\n\n".join(lines) + "\n\n"
                "HWID has been unbound. Login credentials are preserved.\n"
                "The HWID will re-bind on the user's next launch."
            ),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Key Management"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


# ══════════════════════════════════════════════════════════════════════════════
#  Cog
# ══════════════════════════════════════════════════════════════════════════════

class AuthCog(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    # ── /genkey ───────────────────────────────────────────────────────────────
    @app_commands.command(name="genkey", description="Generate one or more Forsaken keys. (Admin)")
    async def genkey(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(GenKeyModal())

    # ── /disablekey ───────────────────────────────────────────────────────────
    @app_commands.command(name="disablekey", description="Disable a key. (Admin)")
    async def disablekey(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(DisableKeyModal())

    # ── /deletekey ────────────────────────────────────────────────────────────
    @app_commands.command(name="deletekey", description="Permanently delete a key. (Admin)")
    async def deletekey(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(DeleteKeyModal())

    # ── /bulkdeletekeys ───────────────────────────────────────────────────────
    @app_commands.command(name="bulkdeletekeys", description="Delete multiple keys at once. (Admin)")
    async def bulkdeletekeys(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(BulkDeleteModal())

    # ── /managekey ────────────────────────────────────────────────────────────
    @app_commands.command(name="managekey", description="View and edit a single key. (Admin)")
    async def managekey(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(ManageKeyModal())

    # ── /managekeys ───────────────────────────────────────────────────────────
    @app_commands.command(name="managekeys", description="Enable or disable multiple keys. (Admin)")
    async def managekeys(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(ManageKeysModal())

    # ── /showallkeys ──────────────────────────────────────────────────────────
    @app_commands.command(name="showallkeys", description="List all keys with full details. (Admin)")
    async def showallkeys(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return

        await interaction.response.defer(ephemeral=True)

        all_keys = get_all_keys()
        if not all_keys:
            await interaction.followup.send("No keys in the database.", ephemeral=True)
            return

        # Build pages of up to 5 keys each to stay under Discord's 2000-char limit
        pages: list[str] = []
        current_lines: list[str] = []

        for key, rec in all_keys.items():
            gen_user = "—"
            if rec.get("generated_by"):
                m = interaction.guild.get_member(rec["generated_by"])
                gen_user = str(m) if m else f"ID:{rec['generated_by']}"

            claimed_user = "—"
            if rec.get("claimed_by_discord"):
                m = interaction.guild.get_member(rec["claimed_by_discord"])
                claimed_user = str(m) if m else f"ID:{rec['claimed_by_discord']}"

            pw_raw = rec.get("password_hash") or "—"
            # Spoiler the password hash
            pw_display = f"||{pw_raw}||" if pw_raw != "—" else "—"

            block = (
                f"```\n"
                f"Key      : {key}\n"
                f"Duration : {rec.get('duration', '—')}\n"
                f"Status   : {'DISABLED' if rec.get('disabled') else 'ACTIVE'}\n"
                f"GenBy    : {gen_user}\n"
                f"Claimed  : {claimed_user}\n"
                f"Username : {rec.get('username') or '—'}\n"
                f"HWID     : {rec.get('hwid') or 'unbound'}\n"
                f"Reg'd    : {(rec.get('registered_at') or '—')[:19]}\n"
                f"```\n"
                f"Password (spoiler): {pw_display}\n"
                f"{'─' * 30}"
            )
            current_lines.append(block)

            # Flush page every 5 keys
            if len(current_lines) >= 5:
                pages.append("\n".join(current_lines))
                current_lines = []

        if current_lines:
            pages.append("\n".join(current_lines))

        total = len(all_keys)
        for i, page in enumerate(pages, 1):
            header = f"## All Keys — Page {i}/{len(pages)}  ({total} total)\n\n"
            view = ui.LayoutView()
            view.add_item(ui.Container(
                ui.TextDisplay(header + page),
                ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
                ui.TextDisplay("-# Forsaken Bot — Key Management"),
            ))
            await interaction.followup.send(view=view, ephemeral=True)

    # ── /hwidreset ────────────────────────────────────────────────────────────
    @app_commands.command(name="hwidreset", description="Reset HWID binding on one or more keys. (Admin)")
    async def hwidreset(self, interaction: discord.Interaction):
        if not _is_founder(interaction.user):
            await interaction.response.send_message("Admin only.", ephemeral=True)
            return
        await interaction.response.send_modal(HwidResetModal())

    # ── /register ─────────────────────────────────────────────────────────────
    @app_commands.command(name="register", description="Claim your key and create your loader account.")
    async def register(self, interaction: discord.Interaction):
        # Anyone can attempt to register — the key itself is the gate.
        # If they already have the customer role, let them know.
        if _is_customer(interaction.user):
            await interaction.response.send_message(
                "You're already registered. If you need help, open a support ticket.",
                ephemeral=True,
            )
            return
        await interaction.response.send_modal(RegisterModal())

    # ── /download ─────────────────────────────────────────────────────────────
    @app_commands.command(name="download", description="Get the Forsaken download link.")
    async def download(self, interaction: discord.Interaction):
        if not _is_customer(interaction.user):
            await interaction.response.send_message(
                "You need to be a registered customer to download. Use `/register` first.",
                ephemeral=True,
            )
            return

        if DOWNLOAD_LINK == "https://PLACEHOLDER_SET_ME":
            await interaction.response.send_message(
                "The download link hasn't been configured yet. Contact an admin.",
                ephemeral=True,
            )
            return

        view = ui.LayoutView()
        view.add_item(ui.Container(
            ui.TextDisplay("## Download Forsaken"),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay(
                f"Click the link below to download the latest version.\n\n"
                f"[**Download**]({DOWNLOAD_LINK})\n\n"
                f"Use your **username** and **password** to log in to the loader.\n"
                f"Your HWID will bind automatically on first launch.\n\n"
                f"-# Do not share this link."
            ),
            ui.Separator(visible=True, spacing=discord.SeparatorSpacing.small),
            ui.TextDisplay("-# Forsaken Bot — Download"),
        ))
        await interaction.response.send_message(view=view, ephemeral=True)


async def setup(bot: commands.Bot):
    await bot.add_cog(AuthCog(bot))
